In [28]:
import numpy as np
# 1次元配列を作成
A = np.array([1, 2, 3, 4])
print(A)
# 配列の次元数を返す
np.ndim(A)
A.shape
A.shape[0]

[1 2 3 4]


4

In [29]:
# “2次元の配列を作成
B = np.array([[1,2],[3,4],[5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
np.ndim(B) # 配列の次元数を返す

2

In [31]:
B.shape # 配列の要素数を次元毎に返す

(3, 2)

In [32]:
# 行列の内積
# 準備１
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

In [33]:
# 準備２
B = np.array([[5,6],[7,8]])
B.shape

(2, 2)

In [34]:
# dot積 [[1*5+2*7, 1*6+2*8],[3*5+4*7,3*6+4*8]]
# 行列の内積は、左側の行列の行（横方向）と右側の行列“の列（縦方向）の間の要素ごとの積とその和によって計算が行われる
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [35]:
#  2*3の行列の内積
A = np.array([[1,2,3],[4,5,6]])
A.shape

(2, 3)

In [36]:
B = np.array([[1,2],[3,4],[5,6]])
B.shape

(3, 2)

In [37]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [39]:
C = np.array([[1,2],[3,4]])
C.shape

(2, 2)

In [40]:
A.shape

(2, 3)

In [43]:
# 要素数が揃っていない場合、内積の計算はできない
np.dot(A,C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [73]:
D = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
D.shape

(3, 2, 4)

In [77]:
E = np.dot(C,D)
E.shape

(2, 3, 4)