In [19]:
# 各層における信号伝達の実装
import numpy as np

X= np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])

# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [20]:
print(W1.shape)

(2, 3)


In [21]:
print(X.shape)

(2,)


In [22]:
print(B1.shape)

(3,)


In [23]:
A1 = np.dot(X, W1) + B1
print(A1)

[ 0.3  0.7  1.1]


In [24]:
# 入力層から第１層への信号の伝達
# 3.4.2_3-18.png

Z1 = sigmoid(A1)
print(A1)

[ 0.3  0.7  1.1]


In [25]:
print(Z1)

[ 0.57444252  0.66818777  0.75026011]


In [26]:
# 第１層から第２層への信号の伝達 
# 3.4.2_3-19.png
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3,0.6]])
B2 = np.array([0.1,0.2])

In [27]:
print(Z1.shape)

(3,)


In [28]:
print(W2.shape)

(3, 2)


In [29]:
print(B2.shape)

(2,)


In [30]:
A2= np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

In [32]:
print(A2)

[ 0.51615984  1.21402696]


In [33]:
print(Z2)

[ 0.62624937  0.7710107 ]
