In [52]:
# 各層における信号伝達の実装
import numpy as np

X= np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])

# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [53]:
print(W1.shape)

(2, 3)


In [54]:
print(X.shape)

(2,)


In [55]:
print(B1.shape)

(3,)


In [56]:
A1 = np.dot(X, W1) + B1
print(A1)

[ 0.3  0.7  1.1]


In [57]:
# 入力層から第１層への信号の伝達
# 3.4.2_3-18.png

Z1 = sigmoid(A1)
print(A1)

[ 0.3  0.7  1.1]


In [58]:
print(Z1)

[ 0.57444252  0.66818777  0.75026011]


In [59]:
# 第１層から第２層への信号の伝達 
# 3.4.2_3-19.png
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3,0.6]])
B2 = np.array([0.1,0.2])

In [60]:
print(Z1.shape)

(3,)


In [61]:
print(W2.shape)

(3, 2)


In [62]:
print(B2.shape)

(2,)


In [63]:
A2= np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

In [64]:
print(A2)

[ 0.51615984  1.21402696]


In [65]:
print(Z2)

[ 0.62624937  0.7710107 ]


In [66]:
# 第二層から出力層への伝達
def identity_function(x):
    return x

W3 = np.array([[0.1,0.3], [0.2, 0.4]])
B3 = np.array([0.1,0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3) # もしくはY = A3
print(Y)

[ 0.31682708  0.69627909]


In [70]:
# 実装まとめ
def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])

    return network

def forward(netwek, x):
    W1, W2, W3 = network['W1'],network['W2'],network['W3']
    b1, b2, b3 = network['b1'],network['b2'],network['b3']

    a1 = np.dot(x,W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)

    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[ 0.31682708  0.69627909]
