In [19]:
# 各層における信号伝達の実装
import numpy as np

X= np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])

# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


In [20]:
print(W1.shape)

(2, 3)


In [21]:
print(X.shape)

(2,)


In [22]:
print(B1.shape)

(3,)


In [23]:
A1 = np.dot(X, W1) + B1
print(A1)

[ 0.3  0.7  1.1]


In [24]:
Z1 = sigmoid(A1)
print(A1)

[ 0.3  0.7  1.1]


In [25]:
print(Z1)

[ 0.57444252  0.66818777  0.75026011]
