- ソフトマックス関数とは分類問題に用いる関数。
- 分類問題とは
 - データがどのクラスに属するか、という問題です。たとえば、人の写った画像から、その人が男性か女性のどちらであるかを分類するような問題

### 分類問題で使われるソフトマックス関数
$$  y_k = \frac{\exp(a_k)}{ \displaystyle \sum_{i=1}^{n} \exp(a_i) } $$

In [2]:
import numpy as np
a = np.array([0.3,2.9,4.0])

exp_a = np.exp(a) # 指数関数
print(exp_a)

[  1.34985881  18.17414537  54.59815003]


In [3]:
sum_exp_a = np.sum(exp_a) # 指数関数の和
print(sum_exp_a)

74.1221542102


In [5]:
y = exp_a / sum_exp_a
print(y)

[ 0.01821127  0.24519181  0.73659691]


In [8]:
# ソフトマックス関数の実装
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a  /sum_exp_a
    
    return y

### ソフトマックス関数の実装改善案
$$  \begin{align}y_k = \frac{\exp(a_k)}{ \displaystyle \sum_{i=1}^{n} \exp(a_i) } &= \frac{\mathrm{C} {\exp(a_k)}}{ \mathrm{C} {\displaystyle \sum_{i=1}^{n} \exp(a_i)}}  \\
&= \frac{\exp(a_k + \log \mathrm{C})}{\displaystyle \sum_{i=1}^{n} \exp(a_i + \log \mathrm{C})} \\
&= \frac{\exp(a_k + \mathrm{C'})}{\displaystyle \sum_{i=1}^{n} \exp(a_i + \mathrm{C'})}
\end{align} 
$$

In [9]:
a = np.array([1010,1000,990])
np.exp(a) / np.sum(np.exp(a)) # ソフトマックス関数の計算 （正しく計算されない）

/Users/kesuuyof/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app
/Users/kesuuyof/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


array([ nan,  nan,  nan])

In [10]:
c = np.max(a)
a - c

array([  0, -10, -20])

In [11]:
np.exp(a-c) / np.sum(np.exp(a-c))

array([  9.99954600e-01,   4.53978686e-05,   2.06106005e-09])

In [12]:
# 改良版ソフトマックス関数
def softmax(a):
    c =np.max(a)
    exp_a = np.exp(a-c) # オーバーフロー対策
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [13]:
a = np.array([0.3,2.9,4.0])
y = softmax(a)
print(y)

[ 0.01821127  0.24519181  0.73659691]


In [14]:
np.sum(y) # ソフトマックス関数の出力を「確率」として解釈することができる

1.0