# バッチ版Affineレイヤ
## バッチ版Affineレイヤの計算グラフ

![バッチ版Affineレイヤの計算グラフ](https://files.slack.com/files-tmb/T0FNB0BP1-F4M995Y14-307d3b2582/____________________________2017-03-20_15.16.57_1024.png)

異なる点は入力であるXの形状が(N,2)になっただけ。


順伝播の際のバイアスの加算はX・Wに対して、バイアスがそれぞれのデータに加算される。

In [8]:
import numpy as np
# バイアスの加算について (順伝播)
X_dot_W = np.array([[0,0,0],[10,10,10]])
B= np.array([1,2,3])

print(X_dot_W)
print(X_dot_W + B)

[[ 0  0  0]
 [10 10 10]]
[[ 1  2  3]
 [11 12 13]]


In [10]:
# バイアスの加算の逆伝播 データが2個（N=2）あるものと仮定
dY = np.array([[1,2,3],[4,5,6]])
dY

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# np,sum()で、0番目の塾（データを単位とした軸）に対して(axis=0)の総和を求める。
dB = np.sum(dY, axis=0)
dB

array([5, 7, 9])

In [20]:
# Affineの実装
import numpy as np
import common

class Affine:
    def __init__(self, w, b):
        self.w = w
        self.b = b
        self.x = None
        self.dw = None
        self.db = None
        
    def forward(self, x):
        self.x = x
        out = np.dot(x,selfw) + self.b
        
        return out
    
    def backward(self, dout):
        dx = np.dot(dout, self.W.T)
        self.dw = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)
        
        return dx